version: 2
archives:
- files:
  - README.md
  - CHANGELOG.md
  - LICENSE-BlueOak.md
  - LICENSE-MIT.md
  builds:
  - redact-ext-1password
  format: tgz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"
builds:
- id: redact-ext-1password
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X main.version={{.Version}}
  main: .
  targets:
  - darwin_arm64
  - darwin_amd64
  - linux_amd64
  - windows_amd64
checksum:
  name_template: 'SHA256SUMS.{{.ProjectName}}-{{.Version}}'
project_name: redact-ext-1password
release:
  github:
    name: redact-ext-1password
    owner: julian7
snapshot:
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"
universal_binaries:
- id: redact-ext-1password
  name_template: "redact-ext-1password"
  replace: true
